# Generated by Django 2.0.5 on 2018-05-11 03:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.models
from wagtail.images import get_image_model_string


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_embed_videos', '0002_collections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embedvideo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='embedvideo',
            name='thumbnail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=get_image_model_string(), verbose_name='Thumbnail'),
        ),
        migrations.AlterField(
            model_name='embedvideo',
            name='uploaded_by_user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Uploader'),
        ),
    ]
